### ISSUE TITLE
How to get digit datasets?

### ISSUE THREAD

**Issue by junwoopark92** [VisionLearningGroup/VisionLearningGroup.github.io#3]
Hi.

I wonder how to get the preprocessed mnist, usps,  etc.

The data obtained publicly differs from the data used by this repository.

Thank you.

**Comment by xcpeng** [comment]
Since many researchers have sent us emails for Digit-Five data. We share the Digit-Five dataset we use in our experiments in the following download link:

https://drive.google.com/open?id=1A4RJOFj4BJkmliiEL7g9WzNIDUHLxfmm

Keep in mind that the Mnist-M dataset is generated by ourselves, thus this subset may be different from the one released by DANN paper.

If you find the Digit-Five dataset useful for your research, please cite our paper.
