### ISSUE TITLE
How to get the digital dataset like mnist_data.mat?

### ISSUE THREAD

**Issue by meiyuan666** [VisionLearningGroup/VisionLearningGroup.github.io#4]
Hi
I gained a lot from your paper, but I encountered some problems in the experiment.I can't find the digital dataset,just like mnist_data.mat.Can you share your digital dataset?Thank you very much!
Best wishes!

**Comment by xcpeng** [comment]
Since many researchers have sent us emails for Digit-Five data. We share the Digit-Five dataset we use in our experiments in the following download link:

https://drive.google.com/open?id=1A4RJOFj4BJkmliiEL7g9WzNIDUHLxfmm

Keep in mind that the Mnist-M dataset is generated by ourselves, thus this subset may be different from the one released by DANN paper.

If you find the Digit-Five dataset useful for your research, please cite our paper.
